language: scala

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - gem install fakes3
  - fakes3 -r ./fakes3_root -p 9444 &
  - sbt -Dfake.awsS3Endpoint="http://localhost:9444/" test
